### ISSUE TITLE
Korrupte Datenbank

### ISSUE THREAD

**Issue by ooglyhLL** [mediathekview/plugin.video.mediathekview#124]
Ich bekomme gelegentlich eine Fehlermeldung wegen defekter Datenbank (DB). Wenn ich die DB dann per Kommandozeile lösche, so dass sie wieder neu aufgebaut wird, geht für eine Weile wieder alles.
Kann man das eventuell etwas benutzerfreundlicher gestalten? Also z.B. Fehlermeldung durchaus anzeigen, aber mit dem Hinweis, es nochmal von vorne zu versuchen (DB automatisch löschen, neu aufbauen). Nach dem zweiten Versuch kann man ja bis zum nächsten Neustart warten, damit das keine Endlosschleife wird.

Gerade STB werden manchmal per Steckerleiste abgeschaltet. Nicht schön, aber Realität. Auch Abstürze kommen gelegentlich vor. Vielleicht liegt der Fehler aber auch im Plugin selbst.

```
2019-04-05 21:16:41.036 T:2963235696  NOTICE: [plugin.video.mediathekview-0.6.2:Store]: Database driver: Internal (sqlite)
2019-04-05 21:16:41.036 T:2963235696  NOTICE: [plugin.video.mediathekview-0.6.2:StoreSQLite]: Using SQLite version 3.26.0, python library sqlite3 version 2.6.0
2019-04-05 21:16:41.041 T:2963235696   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.DatabaseError'>
                                            Error Contents: database disk image is malformed
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/addon.py", line 34, in <module>
                                                PLUGIN.init()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/plugin.py", line 252, in init
                                                if self.database.init():
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/store.py", line 61, in init
                                                return self.database.init(reset, convert)
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/storesqlite.py", line 113, in init
                                                self.conn.execute('pragma journal_mode=off')
                                            DatabaseError: database disk image is malformed
                                            -->End of Python script error report<--
2019-04-05 21:16:41.395 T:3013591920   ERROR: GetDirectory - Error getting plugin://plugin.video.mediathekview/
2019-04-05 21:16:41.398 T:4091621296   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.mediathekview/) failed
```

**Comment by tuxpoldo** [comment]
Danke für die Info. Eigentlich hätte mein Datenbank-Verwaltungsmodul das abfangen müssen, habe aber jetzt verstanden, warum das schief geht. Das ist in der Tat eine hässliche Situation, aber es wird sich wohl nicht vermeiden lassen, dass solche Kisten auch schon mal durch Stecker-Rausziehen abgeschaltet werden - es hat wohl nicht jeder einen feinen Rechner an der Glotze den er dann auch sauber runterfahren kann....
