### ISSUE TITLE
Datenbank zum zweiten Mal beschädigt

### ISSUE THREAD

**Issue by tkste** [mediathekview/plugin.video.mediathekview#128]
Ich habe es zum zweitem Mal geschafft, die interne Datenbank zu korrumpieren: während das DB-Update läuft (nach starten des LibreELEC PC's) vom Android Tablet aus mit Yatse auf das AddOn MediatheView zugegriffen und etwas gesucht --> das Update bricht ab und ab dann gibts nur noch Fehlermeldungen. Im Kodi-Log findet sich dann das:

```
15:59:37.371 T:140496886290176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: no such table: status
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/addon.py", line 35, in <module>
                                                PLUGIN.run()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/plugin.py", line 294, in run
                                                self.show_db_info()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/plugin.py", line 156, in show_db_info
                                                info = self.database.get_status()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/store.py", line 198, in get_status
                                                return self.database.get_status()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/storesqlite.py", line 575, in get_status
                                                cursor.execute('SELECT * FROM `status` LIMIT 1')
                                            OperationalError: no such table: status
                                            -->End of Python script error report<--

Einzige bisher gefundene Abhilfe: MediathekView deinstallieren, Ordner "\plugin.video.mediathekview" in "\\libreelec\Userdata\addon_data" löschen und MedithekView wieder installieren. Nach einigen Minuten ist die DB dann wieder verfügbar.

Versionen: Kodi 17.6 auf LibreELEC 8.2.5, MediatheView 0.6.2 aus dem Kodi Repository. Das Ganze auf einer ZBox CI327 nano.
```

**Comment by tuxpoldo** [comment]
Ich befürchte, dass ich nur etwas an dem Symptom machen kann: eine bessere Behandlung der Korruptions-Fall so dass sich Neuinstallation erübrigt. Der Grund warum das ein gleichzeitiger Zugriff bei Aktualisierung auf Deinem System einen Crash verursacht, dürfte eher darin zu finden sein, dass bei dieser Plattform die Implementierung der Python Libraries wohl anders sein muss und daran kann ich wenig machen. Ich werde auf jeden Fall versuchen, die Behandlung zu verbessern.

**Comment by wessm** [comment]
Ich habe (glaube ich) ein ähnliches Problem; wenn man während dem Update mit Yatse (von einem Android Gerät) Mediathekview verwendet, beschädigt man die Datenbank (ist zumindest schon zweimal passiert).

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4
