### ISSUE TITLE
Datenbankfehler mit Libreelec 9.0.2

### ISSUE THREAD

**Issue by Siggi0904** [mediathekview/plugin.video.mediathekview#130]
Hallo,

ich bekomme seit drei Tagen folgenden Fehler.
Somit läuft das gesamte Addon nicht mehr.

```
2019-07-02 17:35:15.494 T:2749297520   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.DatabaseError'>
                                            Error Contents: database disk image is malformed
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/service.py", line 34, in <module>
                                                SERVICE.init()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/service.py", line 51, in init
                                                self.updater.init(convert=True)
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 88, in init
                                                self.database.init(convert=convert)
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/store.py", line 61, in init
                                                return self.database.init(reset, convert)
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/storesqlite.py", line 113, in init
                                                self.conn.execute('pragma journal_mode=off')
                                            DatabaseError: database disk image is malformed
                                            -->End of Python script error report<--
2019-07-02 17:35:16.070 T:2749297520 WARNING: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.mediathekview/service.py): the python script "/storage/.kodi/addons/plugin.video.mediathekview/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon9xbmcaddon5AddonE
```

**Comment by kruthoff** [comment]
I've had the same error. I've uninstalled the plugin (including all settings) and reinstalled it. It worked after that.

**Comment by tuxpoldo** [comment]
Das scheint der gleiche Fehler wie #128 zu sein. Ich nehme mich der Sache an.

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4
