### ISSUE TITLE
Datenbank Error in Kodi mit OpenElec

### ISSUE THREAD

**Issue by dmi1100** [mediathekview/plugin.video.mediathekview#132]
Hi,

seit gestern funktioniert mediathekview nicht mehr und es findet auch kein Datenbank Update beim Start mehr statt.
Anbei was ich im Logfile gefunden habe:

````
13:42:02.319 T:1532482464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: no such table: status
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/service.py", line 35, in <module>
                                                SERVICE.run()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/service.py", line 64, in run
                                                updateop = self.updater.get_current_update_operation()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 138, in get_current_update_operation
                                                return self._get_next_update_operation(force, full)
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 147, in _get_next_update_operation
                                                status = self.database.get_status()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/store.py", line 198, in get_status
                                                return self.database.get_status()
                                              File "/storage/.kodi/addons/plugin.video.mediathekview/resources/lib/storesqlite.py", line 575, in get_status
                                                cursor.execute('SELECT * FROM `status` LIMIT 1')
                                            OperationalError: no such table: status
                                            -->End of Python script error report<--
13:42:02.432 T:1532482464   ERROR: Previous line repeats 1 times.
13:42:02.432 T:1532482464 WARNING: CPythonInvoker(4, /storage/.kodi/addons/plugin.video.mediathekview/service.py): the python script "/storage/.kodi/addons/plugin.video.mediathekview/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE
13:42:02.523 T:1511916448 WARNING: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.mediathekview/service.py): the python script "/storage/.kodi/addons/plugin.video.mediathekview/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
````

Ich habe das Addon schon mal deinstalliert und wieder installiert, aber leider bislang ohne Erfolg.
Ich bin nicht sehr erfahren was den Umgang mit PuTTY und Linux angeht.

Viele Grüße und über jede Hilfe sehr erfreut
dmi1100

**Comment by tuxpoldo** [comment]
Hi!

So wie es aussieht, scheint das Datenbankfile aus welchen Grund auch immer kaputt gegangen zu sein. Meine Vermutung ist auch, dass der Datenbereich eine Deinstallation des Plugins überlebt, so dass es leider nicht hilft zu deinstallieren und neu zu installieren.
Ursache dafür ist, dass die meisten Kodi-Installationen wohl auf "Sticks" oder ähnliche Hardware läuft, die in der Regel nicht korrekt runtergefahren wird. Das wird sich aber auch nicht vermeiden lassen.
Ich beabsichtige auf jeden Fall in der nächsten Version mehr Funktionen einzubauen, um das Problem zu entschärfen.
Um Dein Problem erst mal kurzfristig zu lösen: Du musst das Datenbankfile komplett löschen. Da ich sehe, dass Du OpenELEC benutzt, kann ich Dir dafür einen genauen Befehl geben. Du verbindest dich mit Putty mit Deiner OpenELEC Box und führst dann folgenden Befehl aus:

````
rm -f /storage/.kodi/userdata/addon_data/plugin.video.mediathekview/
````

**Comment by tuxpoldo** [comment]
p.S.: Sollte sich das Problem wiederholen: kannst Du bitte etwas mehr Logzeilen VOR dem Knaller einfügen? Würde mich mal interessieren, ob er bereits das Update von MV gezogen hatte,,,

**Comment by dmi1100** [comment]
Hi,

vielen dank für die schnelle Hilfe. Nach dem entfernen der Dateien geht es wieder.
Soll ich Dir noch zusätzliche Logzeilen zuschicken?

**Comment by tuxpoldo** [comment]
Sollte es nochmal passiert sein, dann lass mal bitte was rüberkommen....

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4
