### ISSUE TITLE
Error Type: <type 'exceptions.IOError'>

### ISSUE THREAD

**Issue by sju10544** [mediathekview/plugin.video.mediathekview#134]
Hi all,

with Nvidia Shield 2017 (Oreo) and Kodi 18.4 Leia I got the following error after starting Kodi:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/service.py", line 29, in <module>
                                                from resources.lib.service import MediathekViewService
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/service.py", line 17, in <module>
                                                from resources.lib.updater import MediathekViewUpdater
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 24, in <module>
                                                import ijson
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/__init__.py", line 28, in <module>
                                                backend = _default_backend()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/__init__.py", line 24, in _default_backend
                                                return importlib.import_module('ijson.backends.' + backend)
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/importlib/__init__.py", line 37, in import_module
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/backends/yajl2.py", line 12, in <module>
                                                yajl = backends.find_yajl_ctypes(2)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/backends/__init__.py", line 34, in find_yajl_ctypes
                                                so_name = util.find_library('yajl')
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/ctypes/util.py", line 274, in find_library
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/ctypes/util.py", line 99, in _findLib_gcc
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/tempfile.py", line 463, in NamedTemporaryFile
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/tempfile.py", line 275, in gettempdir
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
                                            IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
                                            -->End of Python script error report<--

Mediathekview will not update their database.

Any thoughts?

Regards

Jens

**Comment by hale50** [comment]
Got exactly the same problem on my AFTV 1. generation. Last successful run was 09-29-2019.
Got error already in Kodi 18.3, updated to 18.4, but failure remains. 
Any more logs needed to analyze?
Regards
Chris.

**Comment by sju10544** [comment]
Tried the same plugin with a RPi3 / Kodi 18.2 without any issues. So it seems that this has something to do with the hardware or how they treat the python scripts.

**Comment by Endur** [comment]
No changes on hardware and software, Android, Kodi 18.4. Got the error since some days, similar to the one as sju10544 has gotten, but small diffs

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.OSError'>
Error Contents: [Errno 2] No such file or directory
Traceback (most recent call last):
File "/storage/emulated/0/Android/data/org,xmbc.kodi/files/.kodi/addons/plugin.video.mediathekview/service.py", line 29, in <module>
from resources.lib.service import MediathekViewService
...

It may be the result of a server side change, not sure...

**Comment by Endur** [comment]
May be the *.gz isn't available for download anymore. 
Ich erinnere mich noch gut an das Problem des Entpackens unter Android.

**Comment by sju10544** [comment]
Sorry do disagree but on 2019-10-09 13:49:06.224 T:1937436688  NOTICE: Starting Kodi (18.2 Git:newclock5_18.2-Leia). Platform: Linux ARM 32-bit
everything works like expected. Database *.gz is/was there, DB is up to date, no errors. Just checked the addon as well as the log.
But still have issues with a different hardware (Nvidia Shield). So it would be great, if someone (tuxpoldo) could have a look at this

**Comment by Endur** [comment]
Der  Fehler ist konstant, kann helfen, diesen zu korrigieren, habe Erfahrung. (Linux, C, Perl, Android)...

**Comment by alex1702** [comment]
> Der Fehler ist konstant, kann helfen, diesen zu korrigieren, habe Erfahrung. (Linux, C, Perl, Android)...

Gerne ein PR machen.

**Comment by Endur** [comment]
PR für irgendetwas zu machen, ist mit vollkommen fremd, sorry :(
Ich hatte hier schon einmal geholfen beim Finden von Fehlern.

**Comment by krassle** [comment]
I have exactly the same **ERROR** like @sju10544 on FIRETV Stick gen. 1 running KODI 17.6.
Almost two weeks since the last successful update of _filmliste-v2.db_. Removing the db file does not help. Clearing Cache data also doesn't help.

No recent software/plugin changes (v.0.6.2 from 2019-03)

What could be the reason for this? I'm able to further debug or test if needed.

Thanks a lot.

**Here is the log**:

`Starting Kodi (17.6 Git:20171115-9acd2d3). Platform: Android ARM 32-bit
15:16:00.369 T:1104481128  NOTICE: Using Debug Kodi x32 build
15:16:00.370 T:1104481128  NOTICE: Kodi compiled Nov 15 2017 by GCC 4.9.0 for Android ARM 32-bit API level 21 (API level 21)
15:16:00.370 T:1104481128  NOTICE: Running on Amazon AFTM with Android 5.1.1 API level 22, kernel: Linux ARM 32-bit version 3.0.31+
15:16:00.377 T:1104481128  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
15:16:00.378 T:1104481128  NOTICE: Host CPU: ARMv7 Processor rev 0 (v7l), 2 cores available
15:16:00.378 T:1104481128  NOTICE: Product: montoya, Device: montoya, Board: capri - Manufacturer: Amazon, Brand: Amazon, Model: AFTM, Hardware: montoya
...
15:16:10.741 T:1397650920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/service.py", line 29, in <module>
                                                from resources.lib.service import MediathekViewService
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/service.py", line 17, in <module>
                                                from resources.lib.updater import MediathekViewUpdater
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 24, in <module>
                                                import ijson
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/__init__.py", line 28, in <module>
                                                backend = _default_backend()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/__init__.py", line 24, in _default_backend
                                                return importlib.import_module('ijson.backends.' + backend)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/importlib/__init__.py", line 37, in import_module
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/backends/yajl2.py", line 12, in <module>
                                                yajl = backends.find_yajl_ctypes(2)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/backends/__init__.py", line 34, in find_yajl_ctypes
                                                so_name = util.find_library('yajl')
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/ctypes/util.py", line 237, in find_library
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/ctypes/util.py", line 90, in _findLib_gcc
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/tempfile.py", line 307, in mkstemp
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/tempfile.py", line 275, in gettempdir
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-21/lib/python2.7/tempfile.py", line 217, in _get_default_tempdir
                                            IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
                                            -->End of Python script error report<--`

**Comment by Endur** [comment]
Also hier nochmals mein Logfile, ausführlicher:

2019-10-11 16:49:27.637 T:13070  NOTICE: -----------------------------------------------------------------------
2019-10-11 16:49:27.637 T:13070  NOTICE: Starting Kodi (18.4 Git:20190831-3ade758ceb). Platform: Android ARM 32-bit
2019-10-11 16:49:27.637 T:13070  NOTICE: Using Release Kodi x32 build
2019-10-11 16:49:27.637 T:13070  NOTICE: Kodi compiled 2019-09-01 by Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://android.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) for Android ARM 32-bit API level 21 (API level 21)
2019-10-11 16:49:27.637 T:13070  NOTICE: Running on Orbsmart Orbsmart H-01 with Android 6.0.1 API level 23, kernel: Linux ARM 32-bit version 4.1.17-g26a590a-dirty
2019-10-11 16:49:27.637 T:13070  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2019-10-11 16:49:27.638 T:13070  NOTICE: 4 CPU cores available
2019-10-11 16:49:27.638 T:13070  NOTICE: Product: rtk_kylin32, Device: kylin32, Board: unknown - Manufacturer: Orbsmart, Brand: Orbsmart, Model: Orbsmart H-01, Hardware: kylin
2019-10-11 16:49:27.642 T:13070  NOTICE: External storage path = /storage/emulated/0; status = ok
2019-10-11 16:49:27.642 T:13070  NOTICE: ARM Features: Neon enabled
2019-10-11 16:49:27.642 T:13070  NOTICE: special://xbmc/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
2019-10-11 16:49:27.642 T:13070  NOTICE: special://xbmcbin/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets
2019-10-11 16:49:27.642 T:13070  NOTICE: special://xbmcbinaddons/ is mapped to: /data/user/0/org.xbmc.kodi/cache/apk/assets/addons
2019-10-11 16:49:27.642 T:13070  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
2019-10-11 16:49:27.643 T:13070  NOTICE: special://envhome/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files
2019-10-11 16:49:27.643 T:13070  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
2019-10-11 16:49:27.643 T:13070  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
2019-10-11 16:49:27.643 T:13070  NOTICE: special://logpath/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
2019-10-11 16:49:27.643 T:13070  NOTICE: The executable running is: /data/app/org.xbmc.kodi-2/lib/arm/libkodi.so
2019-10-11 16:49:27.647 T:13070  NOTICE: Local hostname: unknown805e4f17edd5
2019-10-11 16:49:27.647 T:13070  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
2019-10-11 16:49:27.648 T:13070  NOTIC

...
2019-10-11 16:49:42.566 T:13121   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 2] No such file or directory
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/service.py", line 29, in <module>
                                                from resources.lib.service import MediathekViewService
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/service.py", line 17, in <module>
                                                from resources.lib.updater import MediathekViewUpdater
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 24, in <module>
                                                import ijson
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/__init__.py", line 28, in <module>
                                                backend = _default_backend()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/__init__.py", line 24, in _default_backend
                                                return importlib.import_module('ijson.backends.' + backend)
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/importlib/__init__.py", line 37, in import_module
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/backends/yajl2.py", line 12, in <module>
                                                yajl = backends.find_yajl_ctypes(2)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.ijson/lib/ijson/backends/__init__.py", line 34, in find_yajl_ctypes
                                                so_name = util.find_library('yajl')
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/ctypes/util.py", line 274, in find_library
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/ctypes/util.py", line 103, in _findLib_gcc
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/subprocess.py", line 394, in __init__
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/subprocess.py", line 1047, in _execute_child
                                            OSError: [Errno 2] No such file or directory
   -->End of Python script error report<--                                         

Auffällig:
  "OSError: [Errno 2] No such file or directory"
is analog zu obigen
  "No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']"
Entpackt wird auf diesem System mit dem nativen /system/bin/gzip, nicht per Python internal.
Leider weiss ich nicht mehr aus dem Gedächtnis, wie man ein detailliertes Log erhält.

**Comment by sju10544** [comment]
O.K. And now?

**Comment by spreeni151** [comment]
Ich konnte im Kodi 18.4 (Android) Addon-Fehlermeldungen und ein nicht funktionierendes Datenbankupdate feststellen, nachdem ich das Modul "ijson" auf die aktuelle Version 2.5 geupdatet hatte. Glücklicherweise hatte ich noch ein Backup mit der Version 2.3 dieses Moduls. 
Ich habe keine Ahnung, was das Modul macht, aber vielleicht hilft diese Info, den Fehler im MediethekView Addon einzugrenzen.

**Comment by Endur** [comment]
Das Modul ijson kann ich hier unter 18.4 Android als installiert nicht finden.
Unter https://github.com/isagalaev/ijson ist Version 2.3 zu finden, von 2016. Ich glaube nicht, dass es hier einen Zusammenhang gibt. Mache gern für Tuxpoldo ein debug ;) falls er ein wenig Zeit hat...

**Comment by vitusson** [comment]
Unter KODi wird dieses verwendet, das Repo was du nennst ist veraltet.
https://github.com/ICRAR/ijson

**Comment by eku** [comment]
Downgrading to Version 2.3 of ```script.module.ijson``` fixes downloading of the database! See ```/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/packages``` for older versions. Just unzip it to ```/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/```.

**Comment by sju10544** [comment]
Can confirm that downgrading script.module.ijson to version 2.3 from 2016 "fixes" the error.

**Comment by Endur** [comment]
Confirmed also! Exactly the subdir /script.module.json/lib/ijson/ has to be replaced with the /ijson/ dir from 2.3 git *.tar,gz or *.zip extracted.

**Comment by sju10544** [comment]
Yep! Change exactly the files who Endur described and it works, but what does it mean to the MediathekView addon itself?

**Comment by Endur** [comment]
The of the MediathekView addon should match the changes of ijson 2.5, I suspect, saw there is also a 2.5.1 version.

Found the original full 2.3 packaged Kodi plugin here also:
https://kodi.freemirror.org/kodi/addons/leia/script.module.ijson/

But I keep the 2.5 addon.xml file from 01.10.2019. May be this stops a possible auto-update.

**Comment by eku** [comment]
@Endur Version 2.5.1 adds some backward compatibility. Did you check if it solves the problem for the ```MediathekView addon```?

**Comment by Endur** [comment]
@ Will check that soon, today, will report here...

**Comment by Endur** [comment]
@eku Tested, but ijson 2.5.1 doesn't solve the issue, I got same error in log as for 2.5.0. Back to 2.3.

**Comment by tuxpoldo** [comment]
OK - I added the module `script.module.ijson` version 2.3 originally on Jan 5 2018 to the official kodi repository. The subsequent updates (2.4 and 2.5) came from other users. If you can confirm that 2.5.1 will solve the problem, I will immidiately create a pull request for the new version. Unfortunately I have no suitable hardware to test with...

**Comment by tuxpoldo** [comment]
OK - my answer was too late. In this case the only possibility I see to solve the problem is to provide means for updating the database **without** using `script.module.ijson`. Initially I decided to use this library because of the fact that there were a lot of devices with really small RAM outside there. Without using `script.module.ijson` the provided json file can only be read by loading it entirely in memory...

**Comment by Endur** [comment]
@Tuxpoldo, thank you for your response.  I have downloaded script.module.ijson 2.4 from
https://kodi.freemirror.org/kodi/addons/leia/script.module.ijson/
and this is also working. The error was introduced with version 2.5  and is still there for 2.5.1.
Have tested this twice.

I use now 2.4 and have automated updates disabled as a workaround.

**Comment by tuxpoldo** [comment]
OK - I will now try to create an alternative update routing that will NOT use `script.module.ijson`. As soon as I'm ready I will publish the version in our beta repository.

**Comment by Endur** [comment]
Skipping ijson is may be best, otherwise you have to follow always their changes... A device able to run Kodi Leia with a lot of plugins may also be able to read the json file into RAM. I will help you with testing, my device here has 2gb RAM only.

**Comment by krassle** [comment]
@Tuxpoldo 
Will this be a problem for all 1GB devices out there(e.g. all amazon firetv stick)? 
Here mem stats from my FireTV Stick running KODi atm:
`shell@montoya:/ $ cat /proc/meminfo                                 
MemTotal:         502916 kB
MemFree:           33492 kB
MemAvailable:     100256 kB
Buffers:            5456 kB
Cached:           124268 kB
SwapCached:         4044 kB
Active:           177096 kB
Inactive:         178780 kB
Active(anon):     114460 kB
Inactive(anon):   114256 kB
Active(file):      62636 kB
Inactive(file):    64524 kB
Unevictable:        1248 kB
Mlocked:               0 kB
SwapTotal:        262140 kB
SwapFree:         116612 kB
Dirty:                28 kB
Writeback:             0 kB
AnonPages:        225388 kB
Mapped:            53836 kB
Shmem:              1304 kB
Slab:              28940 kB
SReclaimable:       6404 kB
SUnreclaim:        22536 kB
KernelStack:        7360 kB
PageTables:        12292 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      513596 kB
Committed_AS:   12555100 kB
VmallocTotal:     483328 kB
VmallocUsed:       25240 kB
VmallocChunk:     388036 kB`

**Comment by hale50** [comment]
As I am just a beneficiary of your analyses, I can only say THANKYOU to everybody who has contributed in analyzing this problem and finding a workaround.
So switching automatic updates to off for Mediathekview and ijson, and unzipping ijson version 2.4 into addon folder fixes the issue for now.
Again thanks to all who have worked on this issue.
Chris

**Comment by sju10544** [comment]
I can only agree. Thank you very much guys for all the work and analyzing the problem.

**Comment by joker-mik** [comment]
> 
> 
> I can only agree. Thank you very much guys for all the work and analyzing the problem.

i also switched back to script.module.ijson 2.4 from https://kodi.freemirror.org/kodi/addons/leia/script.module.ijson/
and disabled the autoupdate
This works for me like a charm

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4
