### ISSUE TITLE
Mediathekview v0.6.2 auf FireTV 4k nicht mehr nutzbar

### ISSUE THREAD

**Issue by Krawei** [mediathekview/plugin.video.mediathekview#138]
Lieber @tuxpoldo und liebe Githubgemeinde,

ich nutze aktuell Mediathekview auf einem Fire Stick 4k mit Kodi 19.0-ALPHA1 Git:20191129-4383a79968 und habe aktuell enorme Probleme, Live-TV zu gucken.

Nach einem Blick ins Kodi-Log sieht es für mich so aus, als ob er Probleme mit Python hat:

2019-12-03 19:14:51.456 T:23650   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ModuleNotFoundError'>
                                            Error Contents: No module named 'StringIO'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/service.py", line 29, in <module>
                                                from resources.lib.service import MediathekViewService
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/service.py", line 17, in <module>
                                                from resources.lib.updater import MediathekViewUpdater
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 29, in <module>
                                                from resources.lib.store import Store
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/store.py", line 11, in <module>
                                                from resources.lib.storemysql import StoreMySQL
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.mediathekview/resources/lib/storemysql.py", line 10, in <module>
                                                import mysql.connector
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.myconnpy/lib/mysql/connector/__init__.py", line 28, in <module>
                                                from mysql.connector.connection import MySQLConnection
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.myconnpy/lib/mysql/connector/connection.py", line 30, in <module>
                                                import StringIO
                                            ModuleNotFoundError: No module named 'StringIO'
                                            -->End of Python script error report<--
2019-12-03 19:14:51.468 T:23546   DEBUG: ------ Window Init (DialogNotification.xml) ------
2019-12-03 19:14:51.468 T:23546   DEBUG: Window DialogNotification.xml was already loaded
2019-12-03 19:14:51.469 T:23546   DEBUG: Alloc resources: 0.03ms
2019-12-03 19:14:51.632 T:23650    INFO: Python script stopped

Das Kodi-Log habe ich unter

https://privatebin.net/?702df655acb9a02f#FDcYZWp6EiJFBXDNaK1ktafqoQHxkMRRjHzKQaondbis

bereitgestellt. Zugangskennwort ist "Kodi".

Ist das Problem bekannt? Kann ich irgendetwas meinerseits tun, um das Problem zu umgehen?

Mit Dank und Gruß,
Krawei

**Comment by Krawei** [comment]
@tuxpoldo @TheSasch @alex1702 @bagbag @Nicklas2751 

Ist hier noch jemand am AddOn-Support für LibreElec/Kodi dran?

Könnt Ihr mir/uns ein Status-Update geben? Das wäre super :)

**Comment by alex1702** [comment]
Von tuxpoldo habe ich schon länger nix mehr gehört, er ist der Hauptentwickler. Ich habe leider im Moment keine Zeit und Lust mich damit zu beschäftigen, obwohl ich das Plugin auch gerne mal nutzte. Die anderen erwähnten haben mit den anderen Projekten zu tun und auch nicht so viel mit Python zu tun.

Eigentlich suchen wir einen Entwickler, der die Haultentwicklung vom Plugin angehen könnte. Aber ich habe nicht mal die Zeit dazu ein News Beitrag zu schreiben oder es im Forum zu posten.

**Comment by codingPF** [comment]
@Krawel,
wenn ich mir das so ansehe, dann sieht das aus als ob du eine MySql DB ansprechen willst?
Kannst du das bestätigen?
Wenn Ja, wäre es ggf. ein gangbarer Weg auf die Sqllite variante zu welchen?

**Comment by Marmos76** [comment]
Moment worüber redet ihr ...
a) Sqllite : eine Datei (mehr oder minder ASCII Textdatei)
b) MySQL : echte Datenbank
das sind komplette unterschiedliche paar Schuhe. 

So viel ich verstanden habe wird die Sqlite Datei aber in beiden Fällen heruntergeladen; um ggfs. wenn gewünscht die (entfernte) MySQL-DB  zu aktualisieren.

**Comment by codingPF** [comment]
Released to official Kodi Repo in v0.6.4
