### ISSUE TITLE
Error when using Kodi headless to update DB

### ISSUE THREAD

**Issue by Uatschitchun** [mediathekview/plugin.video.mediathekview#139]
Hi. I'm running a kodi-headless instance (to update the MySQL server, for Yatse, etc.). 

I have installed mediathekview on this instance, too. As the server (the headless instance) is running 24/7 it should also update the mediathekview DB.

Here's an error caused by "no head":

```
2019-12-03 14:52:33.249 T:139866482407168   ERROR: EXCEPTION: Error: Window is NULL, this is not possible :-)
2019-12-03 14:52:33.250 T:139866482407168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Error: Window is NULL, this is not possible :-)
                                            Traceback (most recent call last):
                                              File "/config/.kodi/addons/plugin.video.mediathekview/service.py", line 35, in <module>
                                                SERVICE.run()
                                              File "/config/.kodi/addons/plugin.video.mediathekview/resources/lib/service.py", line 74, in run
                                                self.updater.update(False)
                                              File "/config/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 206, in update
                                                if self.get_newest_list(full):
                                              File "/config/.kodi/addons/plugin.video.mediathekview/resources/lib/updater.py", line 335, in get_newest_list
                                                self.notifier.show_download_progress()
                                              File "/config/.kodi/addons/plugin.video.mediathekview/resources/lib/notifier.py", line 58, in show_download_progress
                                                self.show_progress_dialog(30955)
                                              File "/config/.kodi/addons/plugin.video.mediathekview/resources/lib/kodi/kodiui.py", line 156, in show_progress_dialog
                                                self.pgdialog.create(heading, message)
                                              File "/config/.kodi/addons/plugin.video.mediathekview/resources/lib/kodi/kodiui.py", line 218, in create
                                                self.pgdialog.create(heading, message)
                                            RuntimeError: Error: Window is NULL, this is not possible :-)
                                            -->End of Python script error report<--
```
Can this be solved somehow?!

**Comment by Uatschitchun** [comment]
Ok, I think this can be solved with using mvaupdate and cron

**Comment by Uatschitchun** [comment]
This one may be close!
