### ISSUE TITLE
Fehlerhafter Datensatz?

### ISSUE THREAD

**Issue by maxberghammer** [mediathekview/plugin.video.mediathekview#197]
Servus!
Ich bekomme seit mehreren Tagen einen Fehler beim DB-Import. Tritt sowohl mit der 0.6.8 als auch mit der releasten 1.0.0 auf. Folgendes wird mir ausgegeben:
`
2021-04-20 11:21:43.848225 ERROR [mvupdate3-1.0.0+matrix.1:StoreMySQL]: Database error: 1366 (22007): Incorrect string value: '\xF0\x9F\x90\x8E f...' for column
 mediathekview.film.title at row 8981
2021-04-20 11:21:43.849084 ERROR [mvupdate3-1.0.0+matrix.1:UpdateFileImport]: Error in data import: 1366 (22007): Incorrect string value: '\xF0\x9F\x90\x8E f...
' for column mediathekview.film.title at row 8981
`
Das ganze passiert sowohl auf meinem dezidierten mariadb-server, auf dem ich die mvupdate3 direkt aufrufe als auch mit dem kodi-addon auf meinen raspberries mit kodi 18.7

EDIT: Auch das manuelle Umstellen der DB und der Tabellen-Collations auf UTF8MB4_GENERAL_CI hat nix gebracht. Die DB hab ich manuell angelegt. Wenn ich die automatisch von mvupdate3 anlegen lasse, wird UTF8_GENERAL_CI gesetzt, obwohl mein server auf UTF8MB4_GENERAL_CI eingestellt ist.

beste Grüße

**Comment by codingPF** [comment]
Konnte ich jetzt auch auf dem docker nachstellen (auf Ubuntu irgendwie nicht)...
Schau ich mir an...
Danke

**Comment by maxberghammer** [comment]
Seltsam...Diese Nacht liefen die Updates sauber durch ohne Fehler. Das letzte mal hatte ich den Fehler, als ich gestern Nachmittag die DB mit der 1.0.0 komplett neu aufgebaut habe...Kannst Du bitte mal schauen, warum das Script die DBs mit UTF8_GENERAL_CI neu erzeugt? Sollte doch UTF8MB4_GENERAL_CI sein, oder?
Danke schonmal!

**Comment by codingPF** [comment]
Es wird `DEFAULT CHARACTER SET utf8; ` gesetzt und je nach MySQL Version wird das dann übersetzt...
`Tables created in the database use utf8 and utf8_general_ci by default for any character columns. `
Das kannst du in deinen Server Settings ändern aber ich sehe da jetzt auch nicht das Problem

**Comment by maxberghammer** [comment]
Hm, seltsam...mein Server sagt, er wäre auf UTF8MB4 eingestellt...muss ich wohl mal weiterforschen. Danke fürs Nachschauen!

**Comment by codingPF** [comment]
Ich habe jetzt alles auf UTF8MB4 umgestellt. Dann kommt der Fehler bei mir nicht mehr.
Das neue Package ist in DEV und Kodi Alpha/Beta Repo.

**Comment by Uatschitchun** [comment]
Hi. Hatte selbiges Problem und bin aufs Alpha Repo umgestiegen. Beim Aufruf von mvaupdate erhalte ich:
```
2021-04-29 10:28:24.735569 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-04-29 10:28:24.762189 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
```
obgleich mein server (mariadb 10.5) auf 
```
character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci
```
eingestellt ist!?
Hatte die DB zuvor sicherheitshalber gedropt...

**Comment by codingPF** [comment]
Welches OS / py / pipe läuft der Client und der Server

**Comment by Uatschitchun** [comment]
OS is Ubuntu 20.04 (focal) with python2.7.18.
It's a bit tricky on focal, as ṕython2 got dropped (still running Kodi 18.9). So there's no pip2 anymore!
MysqlConnector already was 
`mysql-connector 2.1.7` (the fixed version from said Mysql Bug Report)
but I managed to update with
`/usr/bin/python2.7 -m pip install --upgrade mysql-connector`

Sadly I'm not able to test further, as I get:
```
$ ./mvupdate mysql -u kodi -p kodi -v
2021-05-01 10:32:50.905337 INFO [mvupdate-1.0.4:mvupdate]: Python Version2.7.18 (default, Mar  8 2021, 13:02:45) 
[GCC 9.3.0]
2021-05-01 10:32:50.908273 INFO [mvupdate-1.0.4:MediathekViewUpdater]: Last Update 1970-01-01 01:00:00
Traceback (most recent call last):
  File "./mvupdate", line 19, in <module>
    APP.run()
  File "/home/uatschitchun/.kodi.linuxserver/addons/plugin.video.mediathekview/resources/lib/mvupdate.py", line 206, in run
    updateop = self.updater.doUpdate()
  File "/home/uatschitchun/.kodi.linuxserver/addons/plugin.video.mediathekview/resources/lib/updater.py", line 146, in doUpdate
    ufd.downloadFullUpdateFile()
  File "/home/uatschitchun/.kodi.linuxserver/addons/plugin.video.mediathekview/resources/lib/updateFileDownload.py", line 104, in downloadFullUpdateFile
    raise Exception('FullUpdate file size {} smaller than allowed (200MB)'.format(filesize))
Exception: FullUpdate file size 66745021 smaller than allowed (200MB)
```

**Comment by codingPF** [comment]
Das ist soweit ok...die exception habe ich eingebaut damit unvollständig Listen nicht geladen werden...wenn die Liste wieder ok ist, dann läuft das wieder....
Warum gehst du nicht auf py3?

**Comment by Uatschitchun** [comment]
mit mvupdate?
Ich nutze das, was im Add-on mit kommt. Da Kodi 18.9 ist es py2
Wie kann ich denn mvupdate3 separat nutzen?

**Comment by codingPF** [comment]
Kodi19 (Matrix) ist py3 und es gibt auch eine mvupdate3...
Aber mit dem neusten connector solltest du unter py2 auch keine Probleme mehr haben...

**Comment by Uatschitchun** [comment]
Wie gesagt, der Connector war bereits auf v2.1.7 und der Fehler, jetzt, wo die Filmliste wieder funzt, bleibt gleich:
```
$ ./mvupdate mysql -u kodi -p kodi -v 
2021-05-04 07:33:46.815703 INFO [mvupdate-1.0.4:mvupdate]: Python Version2.7.18 (default, Mar  8 2021, 13:02:45) 
[GCC 9.3.0]
2021-05-04 07:33:48.063560 INFO [mvupdate-1.0.4:MediathekViewUpdater]: Last Update 2021-05-04 00:20:03
2021-05-04 07:35:20.402985 INFO [mvupdate-1.0.4:UpdateFileImport]: Starting import of approximately 473663 records from ./Filmliste-akt
2021-05-04 07:35:23.610859 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:23.610897 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:25.725714 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:25.730725 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:27.164815 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:27.168803 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:28.476738 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:28.481330 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:29.769685 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:29.773189 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:31.118497 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:31.121933 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:32.350424 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:32.354212 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:33.619731 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:33.623214 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:34.847199 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:34.850770 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:36.100825 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:36.104488 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:37.380882 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:37.384416 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:38.659284 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:38.662624 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:39.971618 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:39.975111 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:41.292436 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:41.296312 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:42.612401 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:42.616226 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:43.903464 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:43.906742 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:45.189902 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:45.193006 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:46.591566 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:46.594439 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:48.169282 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:48.172759 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:49.469127 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:49.472911 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:50.865442 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:50.869099 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:52.200371 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:52.204037 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:53.529535 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:53.533186 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:54.825691 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:54.829089 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:56.125698 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:56.128808 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:57.414537 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:57.417715 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:35:58.772579 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:35:58.775786 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:00.134254 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:00.137730 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:01.683801 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:01.687586 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:03.151608 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:03.155354 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:05.680003 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:05.684690 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:06.970227 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:06.974049 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:08.268308 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:08.271581 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:09.572331 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:09.576919 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:10.846893 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:10.851244 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:12.104482 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:12.107967 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:13.369897 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:13.373209 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:14.702210 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:14.705754 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:15.993908 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:15.997516 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:19.830672 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:19.834438 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:21.404722 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:21.408218 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:22.967467 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:22.971036 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:24.228551 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:24.232038 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:25.532527 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:25.536298 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:26.828158 ERROR [mvupdate-1.0.4:StoreMySQL]: Database error: unknown encoding: utf8mb4
2021-05-04 07:36:26.831746 ERROR [mvupdate-1.0.4:UpdateFileImport]: Error in data import: unknown encoding: utf8mb4
2021-05-04 07:36:27.436336 WARNING [mvupdate-1.0.4:UpdateFileImport]: Update finished with error(s)
2021-05-04 07:36:28.060293 INFO [mvupdate-1.0.4:UpdateFileImport]: 464771 records processed in 71 sec. Updated: 14771 Inserted: 0 deleted: 622
```

**Comment by codingPF** [comment]
Versuch es mal mit dem 8.x das ist der empfohlene

**Comment by Uatschitchun** [comment]
8.x?

**Comment by codingPF** [comment]
Wenn du 
`pip install mysql-connector-python`
eingibst, dann sollte die Version 8.0.22 installiert werden (wenigstens ist das auf meinem Ubunutu 20 so).
v2.1.7 sollte eigentlich schon länger nicht mehr funktionieren (wegen irgendwelcher BATCH Query geschichten).
Wenn du mit -v -v -v startest, dann bekommst du auch noch mehr output im log.
Dort sollte dann so etwas stehen wir:
`Using MySql connector version xxxx`

Hier mal von meinen Testsystem:
`2021-05-08 12:05:19.948072 INFO [mvupdate-1.0.5:mvupdate]: Python Version2.7.18                                                                                                                             (default, Aug  4 2020, 11:16:42)
2021-05-08 12:05:19.948094 DEBUG [mvupdate-1.0.5:MediathekViewUpdater]: Database                                                                                                                                driver: External (mysql)
2021-05-08 12:05:19.948304 DEBUG [mvupdate-1.0.5:StoreMySQL]: Using MySQL connec                                                                                                                               tor version 8.0.22
2021-05-08 12:05:19.948360 DEBUG [mvupdate-1.0.5:StoreMySQL]: Forcefully disabli                                                                                                                               ng C extension
2021-05-08 12:05:19.960919 DEBUG [mvupdate-1.0.5:StoreMySQL]: Connected to serve                                                                                                                               r localhost running 8.0.22-0ubuntu0.20.04.3
`
und hier noch die MySql Version...
`Server version: 8.0.22-0ubuntu0.20.04.3 (Ubuntu)`

**Comment by Uatschitchun** [comment]
Nach der Installation von `mysql-connector-python` mittels:
```
$ /usr/bin/python2.7 -m pip install mysql-connector-python
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                              
Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Using cached mysql_connector_python-8.0.24-py2.py3-none-any.whl (319 kB)
Requirement already satisfied: protobuf>=3.0.0 in ./.local/lib/python2.7/site-packages (from mysql-connector-python) (3.15.8)
Requirement already satisfied: six>=1.9 in ./.local/lib/python2.7/site-packages (from protobuf>=3.0.0->mysql-connector-python) (1.15.0)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.0.24
```
Und vorheriger deinstallation von `mysql-connector`
```
$ /usr/bin/python2.7 -m pip uninstall mysql-connector
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                              
Found existing installation: mysql-connector 2.2.9
Uninstalling mysql-connector-2.2.9:
  Would remove:
    /home/uatschitchun/.local/lib/python2.7/site-packages/mysql/*
    /home/uatschitchun/.local/lib/python2.7/site-packages/mysql_connector-2.2.9.dist-info/*
    /home/uatschitchun/.local/lib/python2.7/site-packages/mysqlx/*
Proceed (y/n)? y
  Successfully uninstalled mysql-connector-2.2.9
```
Gibt ein `$ ./mvupdate mysql -u kodi -p kodi -v -v -v` das hier:
```
Traceback (most recent call last):
  File "./mvupdate", line 13, in <module>
    from resources.lib.mvupdate import UpdateApp
  File "/home/uatschitchun/.kodi.linuxserver/addons/plugin.video.mediathekview/resources/lib/mvupdate.py", line 23, in <module>
    from resources.lib.updater import MediathekViewUpdater
  File "/home/uatschitchun/.kodi.linuxserver/addons/plugin.video.mediathekview/resources/lib/updater.py", line 15, in <module>
    from resources.lib.storeMySql import StoreMySQL
  File "/home/uatschitchun/.kodi.linuxserver/addons/plugin.video.mediathekview/resources/lib/storeMySql.py", line 10, in <module>
    import mysql.connector
  File "/home/uatschitchun/.local/lib/python2.7/site-packages/mysql/connector/__init__.py", line 53, in <module>
    from .connection import MySQLConnection
  File "/home/uatschitchun/.local/lib/python2.7/site-packages/mysql/connector/connection.py", line 39, in <module>
    from .authentication import get_auth_plugin
  File "/home/uatschitchun/.local/lib/python2.7/site-packages/mysql/connector/authentication.py", line 37, in <module>
    from urllib.parse import quote
ImportError: No module named parse
```
Die Python3 Version (mvupdate3) tut aber, weshalb ich wohl diese nutzen werde für das externe Update der DB

**Comment by codingPF** [comment]
Den Fehler hatte ich auch mal als ich versucht habe von py3 auf py2 zu downgraded.
Py3 ist die richtige Wahl 😉

**Comment by codingPF** [comment]
Released als 1.0.9
