### ISSUE TITLE
WebOS: mysql-Datenbank - "Command '('lsb_release', '-a')' returned non-zero exit status 3"

### ISSUE THREAD

**Issue by falk4243** [mediathekview/plugin.video.mediathekview#226]
Kodi ist mittlerweile auch auf LG WebOS verfügbar ([Alpha](https://mirrors.kodi.tv/nightlies/webos/master/), aber läuft ziemlich gut), wo eine SQLite-Datenbank aus Platzgründen keine Option ist. Kein Problem, dachte ich mir, dann eben per MySQL, allerdings scheitert diese Option an der "lsb_release -a" Abfrage, die unter WebOS lediglich ein nichtssagendes ... 

```
LSB Version:	n/a
Distributor ID:	n/a
Description:	(none)
Release:	n/a
Codename:	n/a
``` 
... ausgibt, was das Plugin dann mit "returned non-zero exit status 3" quittiert und nicht auf die angegebene Datenbank zugreift.

Die OS-Informationen sind unter "/var/run/nyx/info.json" auslesbar, in meinem Fall ...

```
{
    "core_os_kernel_version": "5.4.96-266.mlt4tv.4",
    "core_os_name": "Rockhopper",
    "core_os_release": "7.3.0-2901",
    "core_os_release_codename": "mullet-mebbin",
    "encryption_key_type": "prodkey",
    "webos_build_datetime": "20230507125134",
    "webos_build_id": "2901",
    "webos_imagename": "lib32-starfish-global-secured",
    "webos_manufacturing_version": "03.33.16",
    "webos_name": "webOS TV",
    "webos_prerelease": "",
    "webos_release": "7.3.0",
    "webos_release_codename": "mullet-mebbin",
    "webos_release_platformcode": "7"
}
```

Ist es möglich, die Abfrage so anzupassen, dass die Datenbananbindung auch unter WebOS funktioniert? Wäre super, das Plugin auch dort nutzen zu können, da die nativen Mediathek-Apps, nun sagen wir zu wünschen übrig lassen ...

**Comment by codingPF** [comment]
Aktiv wird das nicht im Addon Abgefragt...es könnte aus dem MySQLConnector kommen...
GGF kannst du mal ein paar Zeilen um den Fehler herum aus dem Log (mit debug) rein kopieren?

**Comment by falk4243** [comment]
Hier die Zeilen aus dem Log - 

```
2023-07-23 21:40:43.519 T:20167   debug <general>: [plugin.video.mediathekview-1.0.13+matrix.1:MediathekViewPlugin]: Database driver: External (mysql)
2023-07-23 21:40:43.520 T:20167   debug <general>: [plugin.video.mediathekview-1.0.13+matrix.1:MediathekViewPlugin]: migrateExtendedSearch False
2023-07-23 21:40:43.520 T:20167    info <general>: [plugin.video.mediathekview-1.0.13+matrix.1:MediathekViewPlugin]: Plugin invoked with parameters {'mode': ['channels']}
2023-07-23 21:40:43.520 T:20167   debug <general>: [plugin.video.mediathekview-1.0.13+matrix.1:MediathekViewPlugin]: start View id 55
2023-07-23 21:40:43.520 T:20167   debug <general>: [plugin.video.mediathekview-1.0.13+matrix.1:MediathekViewPlugin]: start Skin skin.estuary
2023-07-23 21:40:43.520 T:20167   debug <general>: [plugin.video.mediathekview-1.0.13+matrix.1:StoreMySQL]: getChannels
2023-07-23 21:40:43.520 T:20167   debug <general>: [plugin.video.mediathekview-1.0.13+matrix.1:StoreCache]: no cache file request "channels" and condition ""
2023-07-23 21:40:43.520 T:20167   debug <general>: [plugin.video.mediathekview-1.0.13+matrix.1:StoreMySQL]: query: SELECT channel AS channelid, channel, 0 as count FROM film GROUP BY channel ORDER BY channel ASC params None
2023-07-23 21:40:43.520 T:20167   debug <general>: [plugin.video.mediathekview-1.0.13+matrix.1:StoreMySQL]: Using MySQL connector version 8.0.18
2023-07-23 21:40:43.547 T:20167   error <general>: [plugin.video.mediathekview-1.0.13+matrix.1:StoreMySQL]: Database error: Command '('lsb_release', '-a')' returned non-zero exit status 3.
2023-07-23 21:40:43.553 T:19947   debug <general>: ------ Window Init (DialogNotification.xml) ------
2023-07-23 21:40:43.585 T:20167   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'subprocess.CalledProcessError'>
                                                   Error Contents: Command '('lsb_release', '-a')' returned non-zero exit status 3.
                                                   Traceback (most recent call last):
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/plugin.video.mediathekview/addon.py", line 26, in <module>
                                                       PLUGIN.run()
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/plugin.video.mediathekview/resources/lib/plugin.py", line 184, in run
                                                       ui.generate(self.database.getChannels())
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/plugin.video.mediathekview/resources/lib/storeQuery.py", line 295, in getChannels
                                                       rs = self.execute(sql)
                                                            ^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/plugin.video.mediathekview/resources/lib/storeMySql.py", line 78, in execute
                                                       return super(StoreMySQL, self).execute(aStmt, aParams)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/plugin.video.mediathekview/resources/lib/storeQuery.py", line 66, in execute
                                                       cursor = self.getConnection().cursor()
                                                                ^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/plugin.video.mediathekview/resources/lib/storeMySql.py", line 57, in getConnection
                                                       self.conn = mysql.connector.connect(**connectargs)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.myconnpy/lib/mysql/connector/__init__.py", line 177, in connect
                                                       return MySQLConnection(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.myconnpy/lib/mysql/connector/connection.py", line 104, in __init__
                                                       self.connect(**kwargs)
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.myconnpy/lib/mysql/connector/abstracts.py", line 778, in connect
                                                       self.config(**kwargs)
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.myconnpy/lib/mysql/connector/abstracts.py", line 405, in config
                                                       self._add_default_conn_attrs()
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.myconnpy/lib/mysql/connector/connection.py", line 126, in _add_default_conn_attrs
                                                       os_ver = "-".join(linux_distribution()[0:2])
                                                                         ^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.myconnpy/lib/mysql/connector/utils.py", line 431, in linux_distribution
                                                       distro = _parse_lsb_release_command()
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.myconnpy/lib/mysql/connector/utils.py", line 399, in _parse_lsb_release_command
                                                       stdout = subprocess.check_output(
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/subprocess.py", line 466, in check_output
                                                       return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/subprocess.py", line 571, in run
                                                       raise CalledProcessError(retcode, process.args,
                                                   subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 3.
                                                   -->End of Python script error report<--
                                                   
2023-07-23 21:40:43.587 T:20167   debug <general>: onExecutionDone(9, /media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/plugin.video.mediathekview/addon.py)
2023-07-23 21:40:43.659 T:20167   debug <general>: Python interpreter stopped
```

**Comment by codingPF** [comment]
Das scheint im connector vergraben zu sein. Das Plugin/Script dazu findest du im Stacktrace (script.module.myconnpy) ganz unten im Log.
Bitte wende dich an die Entwickler ggf können sie helfen.
