### ISSUE TITLE
Database schema change exception on start of a new, fresh installation.

### ISSUE THREAD

**Issue by domschl** [mediathekview/plugin.video.mediathekview#32]
Reported by nicklas:
```
19:10:14.090 T:139912547092224  NOTICE: [plugin.video.mediathekview-0.3.4:Service]: Startup
19:10:14.091 T:139912547092224  NOTICE: [plugin.video.mediathekview-0.3.4:MediathekViewUpdater]: Database driver: Internal (sqlite)
19:10:14.091 T:139912547092224  NOTICE: [plugin.video.mediathekview-0.3.4:StoreMySQL]: Using SQLite version 3.19.3, python library sqlite3 version 2.6.0
19:10:14.091 T:139912566175488  NOTICE: [plugin.video.mediathekview-0.3.4:StoreMySQL]: ===== RESET: Database will be deleted and regenerated =====
19:10:14.621 T:139912547092224  NOTICE: Previous line repeats 1 times.
19:10:14.621 T:139912547092224   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: database schema has changed
                                            Traceback (most recent call last):
                                              File "/home/nicklas/.kodi/addons/plugin.video.mediathekview/service.py", line 100, in <module>
                                                service.Init()
                                              File "/home/nicklas/.kodi/addons/plugin.video.mediathekview/service.py", line 69, in Init
                                                self.updater.Init()
                                              File "/home/nicklas/.kodi/addons/plugin.video.mediathekview/classes/updater.py", line 30, in Init
                                                self.db.Init()
                                              File "/home/nicklas/.kodi/addons/plugin.video.mediathekview/classes/store.py", line 33, in Init
                                                self.db.Init( reset )
                                              File "/home/nicklas/.kodi/addons/plugin.video.mediathekview/classes/storesqlite.py", line 35, in Init
                                                self._handle_database_initialization()
                                              File "/home/nicklas/.kodi/addons/plugin.video.mediathekview/classes/storesqlite.py", line 710, in _handle_database_initialization
                                                """ )
                                            OperationalError: database schema has changed
                                            -->End of Python script error report<--
19:10:14.632 T:139912547092224 WARNING: CPythonInvoker(2, /home/nicklas/.kodi/addons/plugin.video.mediathekview/service.py): the python script "/home/nicklas/.kodi/addons/plugin.video.mediathekview/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon9xbmcaddon5AddonE
19:10:14.855 T:139912566175488  NOTICE: [plugin.video.mediathekview-0.3.4:Service]: Starting up...
19:10:14.855 T:139912566175488  NOTICE: [plugin.video.mediathekview-0.3.4:Service]: Initiating full update...
19:10:14.855 T:139912566175488  NOTICE: [plugin.video.mediathekview-0.3.4:MediathekViewUpdater]: Opening https://res.mediathekview.de/akt.xml

```

**Comment by tuxpoldo** [comment]
Hier das Logfile von @Nicklas2751 
[kodi.log](https://github.com/mediathekview/plugin.video.mediathekview/files/1628483/kodi.log)

**Comment by tuxpoldo** [comment]
Das hier ist die kritische Stelle:

```
19:10:14.091 T:139912566175488  NOTICE: [plugin.video.mediathekview-0.3.4:StoreMySQL]: ===== RESET: Database will be deleted and regenerated =====
19:10:14.621 T:139912547092224  NOTICE: Previous line repeats 1 times.
```
Das ist der Beweis, dass auf manchen Systemen bei der Installation (und wie wir nun wissen auch beim Update) der Service-Thread mehrfach gestartet wird. Dieses Problem ist übel uns sollte so schnell wie möglich behoben werden.

Es wurde bis jetzt nur auf reinem Linux (also nicht Android) beobachtet - auch auf LibreELEC, ist aber nicht zuverlässig reproduzierbar.

**Comment by Wikinaut** [comment]
Ich installierte gestern erstmals das Plugin auf OSMC auf Raspberry 3. Nachdem mir alles sehr langsam schien. installierte ich MySQL (MariaDB), einen Benutzer und die Datenbank. Dann gingen die Probleme los.

Inzwischen hat das System zumindest eine differentielle Datei geladen, aber der Gesamtdownload sollte auch per Menü triggerbar sein. Dazu werde ich ggfs. noch ein separates Issue aufmachen. 

Eventuell - falls noch nicht so gemacht - sollte man dies tun:

```
DROP TABLE IF EXISTS `mediathekview`;
CREATE TABLE IF NOT EXISTS `mediathekview` ( ... );
```

**Comment by domschl** [comment]
In #16 gibts schon den feature request für einen DB-update button.

**Comment by Wikinaut** [comment]
@domschl super, danke. (Hatte ich gestern auch gelesen, aber leider verdrängt....)

**Comment by tuxpoldo** [comment]
Ich konnte inzwischen sogar auf dem Mac das Verhalten nachstellen (Bei Installation/Update aus dem Repository wird der Service-Thread manchmal mehrmals gestartet).

Da ein hohes Maß an Isolation zwischen allen Instanzierungen des Addons existiert, ist es nicht so einfach das Problem zu lösen. Der Erste Versuch folgt nun....

**Comment by tuxpoldo** [comment]
Der scheint auch zu funktionieren. Nachfolgend kann man sehen, wie erst die Instanz `93f17fd5fc94640fd51478d0e2ab1865` und dann die Instanz `d224c56ba3c1383c9ebcdfc356b00786` startet. Der letzte gewinnt und der vorherige fügt sich seinem Schicksal und fährt runter.

```
16:26:06.615 T:123145372061696  NOTICE: [plugin.video.mediathekview-0.4.0.3:Service]: Init (instance id: 93f17fd5fc94640fd51478d0e2ab1865)
16:26:06.643 T:123145372061696  NOTICE: [plugin.video.mediathekview-0.4.0.3:Updater]: Database driver: Internal (sqlite)
16:26:06.643 T:123145372061696  NOTICE: [plugin.video.mediathekview-0.4.0.3:StoreSQLite]: Using SQLite version 3.14.2, python library sqlite3 version 2.6.0
16:26:06.688 T:123145372061696  NOTICE: [plugin.video.mediathekview-0.4.0.3:Service]: Starting up... (instance id: 93f17fd5fc94640fd51478d0e2ab1865)
16:26:06.694 T:123145371525120  NOTICE: [plugin.video.mediathekview-0.4.0.3:Service]: Init (instance id: d224c56ba3c1383c9ebcdfc356b00786)
16:26:06.694 T:123145371525120  NOTICE: [plugin.video.mediathekview-0.4.0.3:Service]: Found other instance with id d224c56ba3c1383c9ebcdfc356b00786
16:26:06.694 T:123145371525120  NOTICE: [plugin.video.mediathekview-0.4.0.3:Service]: Startup delayed by 1 second(s) waiting the other instance to shut down
16:26:07.697 T:123145372061696  NOTICE: [plugin.video.mediathekview-0.4.0.3:Service]: Shutting down... (instance id: 93f17fd5fc94640fd51478d0e2ab1865)
16:26:07.697 T:123145372061696  NOTICE: [plugin.video.mediathekview-0.4.0.3:Service]: Exit (instance id: 93f17fd5fc94640fd51478d0e2ab1865)
16:26:07.697 T:123145371525120  NOTICE: [plugin.video.mediathekview-0.4.0.3:Updater]: Database driver: Internal (sqlite)
16:26:07.697 T:123145371525120  NOTICE: [plugin.video.mediathekview-0.4.0.3:StoreSQLite]: Using SQLite version 3.14.2, python library sqlite3 version 2.6.0
16:26:07.712 T:123145371525120  NOTICE: [plugin.video.mediathekview-0.4.0.3:Service]: Starting up... (instance id: d224c56ba3c1383c9ebcdfc356b00786)
```
